apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
type: Opaque
stringData:
  PGUSER:     dbuser
  PGPASSWORD: pass123
  PGDATABASE: HomeSharing
  PGHOST:     postgres        # matches the Service name below

